spring:
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rssystemtest?useSSL=false&serverTimezone=UTC


  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto=updat:

server:
  port: 8080